ALTER TABLE IF EXISTS messages ADD COLUMN IF NOT EXISTS unused_dummy INTEGER;
CREATE TABLE IF NOT EXISTS app_files (
    id VARCHAR(50) PRIMARY KEY,
    mime_type VARCHAR(100),
    data BYTEA,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
